### ISSUE TITLE
Compdb documentation

### ISSUE THREAD

**Issue by innerout** [Sarcasm/compdb#11]
Could you update the documentation of the project?
I installed compdb with pip giving different options to pass but i do not know how to use them.
Is it only the -p parameter that should interest the users?

**Comment by Sarcasm** [comment]
Maybe it's the pypi release which is not up-to-date, I should probably make a new release.

If you use the version from Github master, does it work ok?
The README should be up to date, and the `compdb help` should be too.

    pip install --user git+https://github.com/Sarcasm/compdb.git#egg=compdb

**Comment by innerout** [comment]
I will try it and reply soon.Also there were complaints about the documentation and in some issues from the LSP project.One of the issues was this one https://github.com/tomv564/LSP/issues/2 .

**Comment by innerout** [comment]
Sorry for the late answer! I downloaded the compdb the pip way you suggested and everything worked fine thanks.
Lastly before the issue is closed, i had to cd in
 ```~/.local/lib/python3.6/site-packages/compdb/ ```  and run
``` python __main__.py -p path/to/compile_commands.json list > compile_commands.json``` 
Is there a way to execute compdb from anywhere?

**Comment by Sarcasm** [comment]
You should make sure `~/.local/bin` is in your `PATH`,

**Comment by innerout** [comment]
OK i did not know that,its the  first time i am using that path.

**Comment by innerout** [comment]
Before closing this issue the ```~/.local/bin``` path was on my virtual machine installation, when i installed it on my compdb installed in ```/usr/bin```.
