### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by Miaoou** [Sarcasm/compdb#2]
Hello,

Could there be some examples of usage somewhere, starting from an already generated compile_commands.json ? (especially since headerdb doesn't exist anymore).

Thanks !

**Comment by Sarcasm** [comment]
The absence of documentation is on purpose for now, as things move and will continue to move, sorry about that.

If you want a header database, at the moment the solution, I will demonstrate the use with [irony-server](https://github.com/Sarcasm/irony-mode/tree/master/server), a simple CMake-project.

```
pip install --user compdb
compdb version
git clone git@github.com:Sarcasm/irony-mode.git
cd irony-mode/server
mkdir build
cd build
cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
cd ..
cat <<'EOF' > .compdb                                                                                                                                                 (master)
[compdb]
build-dir = build/
complementers = headerdb
EOF
compdb update
compdb list >compile_commands.json
```

**Comment by Miaoou** [comment]
Thanks a lot, this is working well, even on a big project. Still can't make YCM work with headers added anyway, I'll investigate further.

**Comment by Sarcasm** [comment]
What do you mean by "header added"?

**Comment by Miaoou** [comment]
I mean the compile_commands.json that now includes every header of my project. YCM still can't do completion on code inside headers, but this is another issue I guess.

**Comment by Sarcasm** [comment]
Ok, don't hesitate to tell me about this issue if you understand it, this is something headerdb is trying to solve, any edge cases interest me.

**Comment by Miaoou** [comment]
No problem, I'll post the solution if I find it :)

**Comment by Sarcasm** [comment]
For starter, you can do something like:

    $ compdb list path/to/my/header.h
    [
          { "directory": ....
    ....
    ]

Copy-paste the compile command, change the compiler to Clang if that's not already the case see if that compiles.

**Comment by rwols** [comment]
Why is there not something extremely simple like doing
```
$ compdb path/to/compile_commands.json > path/to/compile_commands_with_headers.json
```

**Comment by Sarcasm** [comment]
Because there is an explicit "index" step right now, and because auto-detection of the main compilation database is not yet implemented.

However, I agree this should the be goal.

**Comment by rwols** [comment]
Apologies for my ignorance, but when you talk about the "main" compilation database, are you suggesting one can have a hierarchy of databases? All I've seen in practice is a single JSON file being generated by pretty much every build tool out there. Also, nice job on this project!

**Comment by Sarcasm** [comment]
I meant the initial database generated by the build tool.

However, I refrained talking about this, but one of the goal of compdb may also to aggregate compilation databases.
For example, in the [ROS](http://www.ros.org/) community. they have one build directory per CMake project, but a workspace is composed of multiple CMake projects.
It is sometime convenient to see the workspace as one thing, and compdb can concat the compilation databases into one.

**Comment by Sarcasm** [comment]
Just FYI, in the latest commit I have reworked/simplified a few things, hopefully it will be a saner base for futur development.

I will now try to maintain a section in the README to explain how to generate a compilation database for headers:

- https://github.com/Sarcasm/compdb#generating-a-compilation-database-including-header-files

@rwols: 

I have implemented a simple usage as you recommended, here is how you can generate a compilation database with headers:

    compdb list -p build/ > path/to/compile_commands_with_headers.json
