### ISSUE TITLE
Use with cmake

### ISSUE THREAD

**Issue by rsp4jack** [Sarcasm/compdb#27]
I need to use compdb in cmake. So I try this:
```cmake
execute_process(COMMAND "python.exe" "-m" "compdb" "-p" "build" "list" WORKING_DIRECTORY ${PROJECT_SOURCE_DIR}  ECHO_ERROR_VARIABLE ECHO_OUTPUT_VARIABLE)
```
But it did not effect. CMake generates compile_commands.json after configure, so compdb's output will be overwrited by CMake.

I do not know how to call compdb after CMake generates compile_commands.json. Can anyone help me?

**Comment by ileixe** [comment]
I'm interested in this feature as well. Did you figure out the way?
